[package]
name = "coding_games_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
deunicode = "1.4"

[dependencies.winapi]
version = "0.3.9"
features = ["winuser", "windef"]